# Generated by Django 3.2 on 2021-06-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZigbeeDevice',
            fields=[
                ('ieee_address', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('supported', models.BooleanField()),
                ('friendly_name', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('vendor', models.CharField(max_length=30)),
                ('power_source', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ZigbeeGroups',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=50)),
                ('members', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ZigbeeExposes',
            fields=[
                ('device', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.zigbeedevice')),
                ('exposes', models.JSONField()),
                ('state', models.JSONField()),
            ],
        ),
    ]
